- hosts: 127.0.0.1
  connection: local
  tasks:
  - name: deleted deployment for frontend 
    command: kubectl delete -f deploymentfront.yaml

  - name: deleted deployment for postgres
    command: kubectl delete -f deploymentpostgres.yaml

  - name: deleted deployment for backend 
    command: kubectl delete -f deployment1.yaml
    
  - name: create new deployment for frontend 
    command: kubectl apply -f deploymentfront.yaml

  - name: create deployment for postgres
    command: kubectl apply -f deploymentpostgres.yaml

  - name: create new deployment for backend 
    command: kubectl apply -f deployment1.yaml
